### ISSUE TITLE
Bug: can jump up on pots, then get stuck behind house in abandoned player house area

### ISSUE THREAD

**Issue by Alignn** [XenonA7/xenons-triblader-mod#4]
![20220721190437_1](https://user-images.githubusercontent.com/18351802/180272955-fd74c4ee-b6b9-47aa-a38a-bcd306dfb75f.jpg)
Using these pots as a platform, I can jump up on the east cliffside, then go north and end up behind the houses and fences. The solar panels have no collision, and there's no way to get back.

Easy enough to get around though: suicide into the pit to restart the room.

**Comment by XenonA7** [comment]
Ah, the results of having to draw collision layers by hand. Good catch, I will add an invisible wall to prevent players from getting on that cliff in the next update.

**Comment by XenonA7** [comment]
Actually no my collision layers were fine, that blue pot is just too tall. Either way, it is fixed for the next update. Thanks.
