### ISSUE TITLE
Bug: "[object Object]" displays when Emelie uses special arts

### ISSUE THREAD

**Issue by Alignn** [XenonA7/xenons-triblader-mod#5]
![20220721200212_1](https://user-images.githubusercontent.com/18351802/180293655-0fc0f056-e01b-4f4b-91fa-5aa33dd35180.jpg)
Haven't tested with other characters yet, started a new game from scratch.

By the way, do NG+ modifiers work with this mod? I switched on No Mercy and Dash Master, but haven't noticed a difference - guessing they get overridden by all the changes needed to make the mod work?

**Comment by XenonA7** [comment]
I can confirm that Dash Master doesn't work if the player is not playing as Lea. The mechanics for a dash are located in the player files (in the directory **\assets\data\players**) and I would imagine that the game would assume that **lea.json** is the one being used. When you play as another character, you are loading a different file.

Regarding Emilie, I have not been able to reproduce that. What is your mod list?

**Comment by Alignn** [comment]
Just the recommended ones from the installation instructions. I did mess up when installing at first, but uninstalled and wiped the entire CrossCode folder before reinstalling both the game and the mods
![cc mods](https://user-images.githubusercontent.com/18351802/180385026-1f780c86-b343-4c9b-a03c-c86993b0141e.png)
.
It looks kind of like a string not found error, but I tried switching to German (and restarting), and still got the issue.
Tried verifying files (and then reinstalling CCLoader), no change.

**Comment by XenonA7** [comment]
What version of Crosscode?

**Comment by XenonA7** [comment]
Ah... This mod only supports English. There would indeed be missing text for other language options. However Emilie's combat arts are stored in a file that isn't touched by my mod, so I don't know how it could be causing that. You can try to disable certain mods using CCLoader to find the culprit.

**Comment by Alignn** [comment]
You were right, it wasn't from this mod - it was https://github.com/CCDirectLink/cc-combat-art-level-extender. My bad!
That one hasn't seen an update in 3 years, but I'll try submitting an issue...
